name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        
    - name: Install dependencies
      run: |
        if [ ! -f package-lock.json ]; then
          npm install
        else
          npm ci
        fi
      
    - name: Build project
      run: npm run build
    
    - name: Create release timestamp
      id: timestamp
      env:
        TZ: 'Asia/Shanghai'
      run: echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
      
    - name: Create zip archive
      run: cd dist && zip -r ../lockscanned_dist_${{ steps.timestamp.outputs.timestamp }}.zip .
      
    - name: Create tar.gz archive
      run: |
        mv dist lockscanned_dist_${{ steps.timestamp.outputs.timestamp }}
        tar czvf lockscanned_dist_${{ steps.timestamp.outputs.timestamp }}.tar.gz lockscanned_dist_${{ steps.timestamp.outputs.timestamp }}
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ steps.timestamp.outputs.timestamp }}
        tag_name: v${{ steps.timestamp.outputs.timestamp }}
        generate_release_notes: true
        files: |
          lockscanned_dist_${{ steps.timestamp.outputs.timestamp }}.zip
          lockscanned_dist_${{ steps.timestamp.outputs.timestamp }}.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
